# Generated by Django 3.1.5 on 2021-02-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternMgmtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_details',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
