# Generated by Django 3.1.5 on 2021-02-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternMgmtApp', '0003_applicationdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdetails',
            old_name='applied_in',
            new_name='field',
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='main_stream',
            field=models.CharField(default='', max_length=50),
        ),
    ]
