# Generated by Django 3.1.5 on 2021-02-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternMgmtApp', '0004_auto_20210218_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
